import { StyleSheet } from "react-native";

export const DRAWER_WIDTH = 300;

export const styles = StyleSheet.create({
  container: {
    zIndex: 999,
    elevation: 24,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.45)",
    zIndex: 999,
  },
  drawer: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    width: DRAWER_WIDTH,
    zIndex: 1000,
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 24,
  },
  header: {
    paddingBottom: 14,
    paddingHorizontal: 20,
    gap: 4,
  },
  avatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  userName: {
    fontSize: 16,
    lineHeight: 20,
  },
  menuScroll: {
    flex: 1,
  },
  menuContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 32,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    gap: 14,
  },
  iconBox: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  rowLabel: {
    flex: 1,
    fontSize: 15,
  },
  toggleWrapper: {
    alignItems: "flex-end",
    gap: 2,
  },
  chevron: {
    width: 8,
    height: 8,
    borderRightWidth: 2,
    borderTopWidth: 2,
    transform: [{ rotate: "45deg" }],
  },
});

export const iconStyles = StyleSheet.create({
  base: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  clockOuter: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#374151",
    position: "absolute",
  },
  clockHand: {
    width: 1.5,
    height: 5,
    backgroundColor: "#374151",
    position: "absolute",
    top: 2,
    left: 9,
    borderRadius: 1,
  },
  langLine1: {
    width: 14,
    height: 1.5,
    backgroundColor: "#374151",
    marginBottom: 2,
  },
  langLine2: {
    width: 10,
    height: 1.5,
    backgroundColor: "#374151",
    marginBottom: 2,
  },
  langLine3: { width: 14, height: 1.5, backgroundColor: "#374151" },
  bankTop: {
    width: 16,
    height: 4,
    backgroundColor: "#374151",
    borderRadius: 1,
    marginBottom: 2,
  },
  bankBottom: {
    width: 16,
    height: 8,
    borderWidth: 1.5,
    borderColor: "#374151",
    borderRadius: 1,
  },
  scheduleOuter: {
    width: 16,
    height: 16,
    borderRadius: 2,
    borderWidth: 1.5,
    borderColor: "#374151",
    position: "absolute",
  },
  scheduleInner: {
    width: 8,
    height: 1.5,
    backgroundColor: "#374151",
    position: "absolute",
    top: 9,
  },
  profileHead: {
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: "#374151",
    position: "absolute",
    top: 0,
  },
  profileBody: {
    width: 14,
    height: 7,
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
    borderWidth: 1.5,
    borderColor: "#374151",
    position: "absolute",
    bottom: 0,
  },
  shield: {
    width: 14,
    height: 16,
    borderWidth: 1.5,
    borderColor: "#374151",
    borderRadius: 3,
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
  },
  infoCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#374151",
  },
  helpCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#374151",
  },
  logoutArrow: {
    width: 12,
    height: 12,
    borderTopWidth: 1.5,
    borderRightWidth: 1.5,
    borderColor: "#374151",
    transform: [{ rotate: "45deg" }],
  },
});
