const en = {
  app_name: "Enatega Deliveries Store App",
  welcome_title: "Store Partner Workspace",
  welcome_subtitle:
    "Theme, localization, and reusable base components are ready.",
  change_theme: "Switch theme",
  change_language: "Switch language",
  current_theme: "Theme mode: {{mode}}",
  current_language: "Language: {{language}}",
  // Auth
  auth_title: "Enter Your Credentials to login",
  auth_subtitle: "We'll check if you have an account",
  auth_email_placeholder: "Email Address",
  auth_password_placeholder: "Password",
  auth_welcome_back: "Welcome Back!",
  auth_access_store: "Access Your Store",
  auth_login_subtitle: "Login to manage your store and orders",
  auth_forgot_password: "Forgot Password?",
  auth_data_protected: "Your data is protected",
  auth_login: "Login",
  auth_login_loading: "Logging in...",
  auth_logout: "Log Out",
  auth_logout_loading: "Logging out...",
  auth_email_required: "Email is required",
  auth_email_invalid: "Enter a valid email address",
  auth_password_required: "Password is required",
  // Bottom nav
  nav_home: "Home",
  nav_wallet: "Wallet",
  nav_earnings: "Earnings",
  nav_profile: "Profile",
  // Home / Orders
  orders_title: "Orders",
  orders_tab_new: "New Order",
  orders_tab_processing: "Processing",
  orders_tab_delivered: "Delivered",
  orders_tab_new_orders: "New Orders",
  orders_tab_in_progress: "In Progress",
  orders_tab_ready: "Ready",
  orders_tab_pickup_short: "Pickup",
  orders_tab_completed: "Completed",
  // Profile
  profile_title: "Profile",
  profile_bank_details: "Bank details",
  profile_updated: "Updated",
  profile_vehicle_plate: "Vehicle Plate",
  profile_address: "Address",
  profile_phone: "Phone No",
  profile_username: "Username",
  profile_wallet_balance: "Wallet Balance",
  profile_theme: "Theme",
  profile_availability: "Availability",
  profile_availability_subtitle: "Let others know you're available",
  profile_account_settings: "Account & Settings",
  profile_language: "Language",
  profile_language_subtitle: "Choose your preferred language",
  profile_bank_management: "Bank Management",
  profile_bank_management_subtitle: "Manage your bank accounts",
  profile_work_schedule: "Work schedule",
  profile_work_schedule_subtitle: "Set your working hours and days",
  work_schedule_select_time: "Select time",
  work_schedule_hour: "Hour",
  work_schedule_minute: "Minute",
  profile_scheduled_orders: "Scheduled Orders",
  profile_scheduled_orders_subtitle: "Track your scheduled orders",
  profile_privacy_policy: "Privacy Policy",
  profile_privacy_policy_subtitle: "Read our privacy policy",
  profile_about_us: "About Us",
  profile_about_us_subtitle: "Learn more about our company",
  profile_help: "Help",
  profile_help_subtitle: "Get help and support",
  profile_logout_subtitle: "Sign out from your account",
  profile_user_profile: "User Profile",
  profile_user_profile_subtitle: "Tap to view profile details",
  profile_not_added: "Not added",
  profile_edit_address: "Edit Address",
  profile_edit_phone: "Edit Phone No",
  profile_update: "Update",
  profile_field_required: "This field is required",

  // Language
  language_title: "Language",
  language_update: "Update Language",

  // Bank Management
  bank_title: "Bank Management",
  bank_currency: "Currency",
  bank_holder_label: "Full Name of the Bank Account Holder",
  bank_holder_placeholder: "e.g. Gabriel Gutkowski",
  bank_holder_required: "Account holder name is required",
  bank_iban_label: "IBAN / Swift / BSB",
  bank_iban_placeholder: "e.g. IT25M0680218128171X4075J102",
  bank_iban_required: "IBAN / Swift / BSB is required",
  bank_account_label: "Account Number",
  bank_account_placeholder: "e.g. 3254465164614411",
  bank_account_required: "Account number is required",
  bank_confirm: "Confirm",
  bank_name_label: "Bank Name",
  bank_name_placeholder: "e.g. Bank of America",
  bank_branch_code_label: "Branch Code",

  // Orders / NewOrdersScreen
  orders_tab_delivery: "Delivery Orders",
  orders_tab_pickup: "Pickup Orders",
  orders_no_more: "No more orders",
  orders_empty_delivery: "No delivery orders",
  orders_empty_pickup: "No pickup orders",

  // OrderCard
  order_card_id_label: "Order ID:",
  order_card_col_order: "ORDER",
  order_card_col_price: "PRICE",
  order_card_total: "Total",
  order_card_comment: "Comment",
  order_card_add_ons: "Add-ons",
  order_card_placed_on: "Placed on:",
  order_card_customer_name: "Customer Name:",
  order_card_address: "Address:",
  order_card_view_map: "View on map",
  order_card_map_open_failed: "Unable to open map",
  order_card_type_delivery: "Delivery",
  order_card_type_pickup: "Pickup",
  order_card_reject: "Reject",
  order_card_accept: "Accept",
  order_card_delivered: "Delivered",
  order_card_rider_arrived: "Rider arrived",
  order_card_preparing: "Preparing",
  order_card_mark_ready: "Mark as Ready",
  order_card_heading_customer: "Heading to Customer",
  order_card_order_status: "Order Status:",
  order_card_confirm_pickup: "Confirm Pickup",
  order_card_rider_name: "Rider Name",
  order_card_payment_method: "Payment method",
  order_card_date_time: "Date & Time",
  order_card_payment_cod: "COD",
  order_card_bill_subtotal: "Subtotal",
  order_card_bill_discount: "Discount",
  order_card_bill_tax: "Tax",
  order_card_bill_packing: "Packing Charges",
  order_card_bill_delivery_fee: "Delivery Fee",
  order_card_bill_tip: "Courier Tip",
  order_card_bill_details: "Bill Details",
  chat_rider: "Rider Chat",
  chat_store: "Store Chat",
  chat_empty: "No messages yet",
  chat_enter_concern: "Enter your concern",
  chat_send: "Send",
  chat_send_failed: "Unable to send message",
  chat_sender_missing: "Unable to identify sender",
  chat_receiver_missing: "Unable to identify receiver",
  chat_contact_restaurant: "Contact Restaurant",
  chat_order_number: "Order number:",
  chat_reply_placeholder: "Send a reply to customer!",
  minutes_abbr: "min",
  no_orders_here: "No orders here yet",
  set_preparing_time: "Set preparing time",
  done: "Done",
  cancel: "Cancel",
  reject_modal_title: "Decline Order",
  reject_modal_order_prefix: "Order",
  reject_modal_description:
    "Please let the customer know why you're declining this order. This will be shared with them.",
  reject_modal_suggested_reasons: "Suggested reasons",
  reject_modal_reason_placeholder: "Write your reason here...",
  reject_modal_confirm: "Reject Order",
  reject_reason_item_out_of_stock: "Item out of stock",
  reject_reason_kitchen_busy: "Kitchen too busy",
  reject_reason_cannot_deliver: "Cannot deliver to location",
  reject_reason_ingredient_unavailable: "Ingredient unavailable",
  reject_reason_closing_soon: "Closing soon",
  reject_reason_order_too_large: "Order is too large",
  reject_reason_other: "Other",

  // Wallet
  wallet_current_balance: "Current Balance",
  wallet_available_for_withdrawal: "Available for withdrawal:",
  wallet_withdraw_now: "Withdraw Now",
  wallet_available_amount_label: "Available Amount",
  wallet_enter_amount: "Enter Amount",
  wallet_confirm_withdraw: "Confirm Withdraw",
  wallet_invalid_amount: "Please enter a valid amount",
  wallet_pending_request: "Pending Request",
  wallet_recent_transactions: "Recent Transactions",
  wallet_no_transactions: "No transactions yet",
  wallet_withdrawal_submitted: "Your request for withdrawal has been submitted",
  wallet_withdrawal_eta: "Usually it takes 1-2 business days",
  wallet_withdrawal_failed: "Withdrawal Failed",
  earnings_no_recent_activity: "No recent activity",
  earnings_activity_will_appear: "Your earnings activity will appear here.",

  Loading: 'Loading...',
  updating: 'Updating...',
  Available: 'Available',
  Unavailable: 'Unavailable',
};

export default en;
