const fr = {
  app_name: "Sip Store",
  welcome_title: "Espace partenaire magasin",
  welcome_subtitle:
    "Theme, localisation et composants de base reutilisables sont prets.",
  change_theme: "Changer le thème",
  change_language: "Changer la langue",
  current_theme: "Mode de thème: {{mode}}",
  current_language: "Langue: {{language}}",
  // Auth
  auth_title: "Entrez vos identifiants pour vous connecter",
  auth_subtitle: "Nous vérifierons si vous avez un compte",
  auth_email_placeholder: "E-mail",
  auth_password_placeholder: "Mot de passe",
  auth_welcome_back: "Bon retour !",
  auth_access_store: "Accédez à votre boutique",
  auth_login_subtitle: "Connectez-vous pour gérer votre boutique et vos commandes",
  auth_forgot_password: "Mot de passe oublié ?",
  auth_data_protected: "Vos données sont protégées",
  auth_login: "Se connecter",
  auth_login_loading: "Connexion...",
  auth_logout: "Se deconnecter",
  auth_logout_loading: "Deconnexion...",
  auth_email_required: "L'e-mail est requis",
  auth_email_invalid: "Entrez une adresse e-mail valide",
  auth_password_required: "Le mot de passe est requis",
  // Bottom nav
  nav_home: "Accueil",
  nav_wallet: "Portefeuille",
  nav_earnings: "Revenus",
  nav_profile: "Profil",
  // Home / Orders
  orders_title: "Commandes",
  orders_tab_new: "Nouvelle",
  orders_tab_processing: "En cours",
  orders_tab_delivered: "Livrée",
  orders_tab_new_orders: "Nouvelles",
  orders_tab_in_progress: "En cours",
  orders_tab_ready: "Prêtes",
  orders_tab_pickup_short: "Ramassage",
  orders_tab_completed: "Terminées",
  // Profile
  profile_title: "Profil",
  profile_bank_details: "Coordonnées bancaires",
  profile_updated: "Mis à jour",
  profile_vehicle_plate: "Plaque du véhicule",
  profile_address: "Adresse",
  profile_phone: "Téléphone",
  profile_username: "Nom d'utilisateur",
  profile_wallet_balance: "Solde du portefeuille",
  profile_theme: "Thème",
  profile_availability: "Disponibilité",
  profile_availability_subtitle: "Indiquez si vous êtes disponible",
  profile_account_settings: "Compte et paramètres",
  profile_language: "Langue",
  profile_language_subtitle: "Choisissez votre langue préférée",
  profile_bank_management: "Gestion bancaire",
  profile_bank_management_subtitle: "Gérez vos comptes bancaires",
  profile_work_schedule: "Planning de travail",
  profile_work_schedule_subtitle: "Définissez vos horaires et jours de travail",
  work_schedule_select_time: "Sélectionner l’heure",
  work_schedule_hour: "Heure",
  work_schedule_minute: "Minute",
  profile_scheduled_orders: "Commandes planifiées",
  profile_scheduled_orders_subtitle: "Suivez vos commandes planifiées",
  profile_privacy_policy: "Politique de confidentialité",
  profile_privacy_policy_subtitle: "Consultez notre politique de confidentialité",
  profile_about_us: "À propos de nous",
  profile_about_us_subtitle: "En savoir plus sur notre entreprise",
  profile_help: "Aide",
  profile_help_subtitle: "Obtenez de l'aide et du support",
  profile_logout_subtitle: "Déconnectez-vous de votre compte",
  profile_user_profile: "Profil utilisateur",
  profile_user_profile_subtitle: "Appuyez pour voir les détails du profil",
  profile_not_added: "Non ajouté",
  profile_edit_address: "Modifier l'adresse",
  profile_edit_phone: "Modifier le téléphone",
  profile_update: "Mettre à jour",
  profile_field_required: "Ce champ est requis",
  // Language
  language_title: "Langue",
  language_update: "Mettre à jour la langue",

  // Orders / NewOrdersScreen
  orders_tab_delivery: "Commandes livraison",
  orders_tab_pickup: "Commandes à emporter",
  orders_no_more: "Plus de commandes",
  orders_empty_delivery: "Aucune commande de livraison",
  orders_empty_pickup: "Aucune commande à emporter",

  // OrderCard
  order_card_id_label: "ID commande :",
  order_card_col_order: "COMMANDE",
  order_card_col_price: "PRIX",
  order_card_total: "Total",
  order_card_comment: "Commentaire",
  order_card_add_ons: "Suppléments",
  order_card_placed_on: "Passée le :",
  order_card_customer_name: "Nom du client :",
  order_card_address: "Adresse :",
  order_card_view_map: "Voir sur la carte",
  order_card_map_open_failed: "Impossible d'ouvrir la carte",
  order_card_type_delivery: "Livraison",
  order_card_type_pickup: "À emporter",
  order_card_reject: "Refuser",
  order_card_accept: "Accepter",
  order_card_delivered: "Livrée",
  order_card_rider_arrived: "Livreur arrivé",
  order_card_preparing: "En préparation",
  order_card_mark_ready: "Marquer comme prêt",
  order_card_heading_customer: "En route vers le client",
  order_card_order_status: "Statut de commande :",
  order_card_confirm_pickup: "Confirmer le ramassage",
  order_card_mark_delivered: "Marquer comme livrée",
  order_card_rider_name: "Nom du livreur",
  order_card_payment_method: "Méthode de paiement",
  order_card_date_time: "Date et heure",
  order_card_payment_cod: "Paiement à la livraison",
  order_card_bill_subtotal: "Sous-total",
  order_card_bill_discount: "Remise",
  order_card_bill_tax: "Taxe",
  order_card_bill_packing: "Frais d'emballage",
  order_card_bill_delivery_fee: "Frais de livraison",
  order_card_bill_tip: "Pourboire livreur",
  order_card_bill_details: "Détails de la facture",
  chat_rider: "Chat du livreur",
  chat_store: "Chat du magasin",
  chat_empty: "Aucun message pour le moment",
  chat_enter_concern: "Entrez votre demande",
  chat_send: "Envoyer",
  chat_send_failed: "Impossible d'envoyer le message",
  chat_sender_missing: "Impossible d'identifier l'expéditeur",
  chat_receiver_missing: "Impossible d'identifier le destinataire",
  chat_contact_restaurant: "Contacter le restaurant",
  chat_order_number: "Numéro de commande :",
  chat_reply_placeholder: "Envoyer une réponse au client !",
  minutes_abbr: "min",
  no_orders_here: "Aucune commande ici pour le moment",
  set_preparing_time: "Définir le temps de préparation",
  done: "Terminé",
  cancel: "Annuler",
  reject_modal_title: "Refuser la commande",
  reject_modal_order_prefix: "Commande",
  reject_modal_description:
    "Veuillez indiquer au client pourquoi vous refusez cette commande. Cette raison lui sera partagée.",
  reject_modal_suggested_reasons: "Raisons suggérées",
  reject_modal_reason_placeholder: "Écrivez votre raison ici...",
  reject_modal_confirm: "Refuser la commande",
  reject_reason_item_out_of_stock: "Article en rupture de stock",
  reject_reason_kitchen_busy: "Cuisine trop occupée",
  reject_reason_cannot_deliver: "Impossible de livrer à cet endroit",
  reject_reason_ingredient_unavailable: "Ingrédient indisponible",
  reject_reason_closing_soon: "Fermeture imminente",
  reject_reason_order_too_large: "Commande trop importante",
  reject_reason_other: "Autre",
  // Bank Management
  bank_title: "Gestion bancaire",
  bank_currency: "Devise",
  bank_holder_label: "Nom complet du titulaire du compte bancaire",
  bank_holder_placeholder: "ex. Gabriel Gutkowski",
  bank_holder_required: "Le nom du titulaire est requis",
  bank_iban_label: "IBAN / Swift / BSB",
  bank_iban_placeholder: "ex. IT25M0680218128171X4075J102",
  bank_iban_required: "IBAN / Swift / BSB est requis",
  bank_account_label: "Numéro de compte",
  bank_account_placeholder: "ex. 3254465164614411",
  bank_account_required: "Le numéro de compte est requis",
  bank_confirm: "Confirmer",
  bank_name_label: "Nom de la banque",
  bank_name_placeholder: "ex. Bank of America",
  bank_branch_code_label: "Code de la succursale",

  // Wallet
  wallet_current_balance: "Solde actuel",
  wallet_available_for_withdrawal: "Disponible pour retrait :",
  wallet_withdraw_now: "Retirer maintenant",
  wallet_available_amount_label: "Montant disponible",
  wallet_enter_amount: "Entrez le montant",
  wallet_confirm_withdraw: "Confirmer le retrait",
  wallet_invalid_amount: "Veuillez entrer un montant valide",
  wallet_pending_request: "Demande en attente",
  wallet_recent_transactions: "Transactions récentes",
  wallet_no_transactions: "Aucune transaction pour le moment",
  wallet_withdrawal_submitted: "Votre demande de retrait a été soumise",
  wallet_withdrawal_eta: "Cela prend généralement 1 à 2 jours ouvrables",
  wallet_withdrawal_failed: "Échec du retrait",
  earnings_no_recent_activity: "Aucune activité récente",
  earnings_activity_will_appear: "Votre activité de gains apparaîtra ici.",
  earnings_order_id: "ID de commande",
  earnings_customer_payment: "Paiement client",
  earnings_order_details: "Détails de la commande",
  earnings_admin_commission: "Commission administrateur",
  earnings_rider_earnings: "Gains du livreur",
  earnings_store_net: "Gains nets du magasin",

  Loading: "Chargement...",
  updating: "Mise à jour...",
  Available: "Disponible",
  Unavailable: "Indisponible",
};

export default fr;
