import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
    gap: 8,
  },
  headerTopGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 6,
  },
  headerInfoItem: {
    flex: 1,
    flexDirection: "row",
    gap: 8,
    alignItems: "flex-start",
  },
  headerIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  headerInfoTextWrap: {
    flex: 1,
    gap: 2,
  },
  headerLabel: {
    fontSize: 12,
    lineHeight: 18,
    color: "#4B5563",
  },
  headerValue: {
    fontSize: 14,
    lineHeight: 20,
    color: "#111827",
  },
  headerStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 1,
    marginBottom: 1,
  },
  headerStatusLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: "#4B5563",
  },
  headerStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#DBEAFE",
    borderColor: "#93C5FD",
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 99,
  },
  headerStatusBadgeGreen: {
    backgroundColor: "#D1FAE5",
    borderColor: "#6EE7B7",
  },
  headerStatusBadgeAmber: {
    backgroundColor: "#FEF3C7",
    borderColor: "#FCD34D",
  },
  headerStatusText: {
    fontSize: 12,
    lineHeight: 16,
    color: "#1D4ED8",
    fontWeight: "500",
  },
  headerStatusTextGreen: {
    color: "#047857",
  },
  headerStatusTextAmber: {
    color: "#B45309",
  },
  customerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  customerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  customerAvatarImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  customerTextWrap: {
    flex: 1,
    gap: 2,
  },
  customerLabel: {
    fontSize: 12,
    lineHeight: 18,
    color: "#4B5563",
  },
  customerName: {
    fontSize: 14,
    lineHeight: 20,
    color: "#111827",
  },
  addressRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  rowIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  addressTextWrap: {
    flex: 1,
    gap: 2,
  },
  addressLabel: {
    fontSize: 12,
    lineHeight: 18,
    color: "#4B5563",
  },
  address: {
    fontSize: 14,
    lineHeight: 20,
    color: "#111827",
  },
  viewMapButton: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 4,
    backgroundColor: "#F9FAFB",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  viewMapText: {
    fontSize: 12,
    lineHeight: 18,
    color: "#4B5563",
  },
  divider: {
    height: 1,
    marginVertical: 4,
  },
  itemsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
    marginTop: 0,
  },
  colHeader: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6B7280",
  },
  colHeaderRight: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6B7280",
    textAlign: "right",
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  foodImageBox: {
    width: 48,
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    overflow: "hidden",
  },
  foodImage: {
    width: "100%",
    height: "100%",
  },
  foodImagePlaceholder: {
    width: "100%",
    height: "100%",
  },
  itemInfo: {
    flex: 1,
    gap: 4,
  },
  itemName: {
    fontSize: 14,
    lineHeight: 20,
    color: "#111827",
  },
  itemOptionsWrap: {
    marginTop: -2,
    gap: 2,
  },
  addOnToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    alignSelf: "flex-start",
  },
  addOnToggleText: {
    fontSize: 12,
    lineHeight: 16,
  },
  itemOptionRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  itemOptionText: {
    fontSize: 12,
    lineHeight: 16,
    flex: 1,
  },
  itemPriceColumn: {
    minWidth: 72,
    alignItems: "flex-end",
    gap: 2,
  },
  itemOptionPricesWrap: {
    marginTop: 2,
    gap: 2,
    alignItems: "flex-end",
  },
  itemOptionPrice: {
    fontSize: 12,
    minWidth: 54,
    textAlign: "right",
  },
  itemOptionPriceGap: {
    minHeight: 16,
  },
  itemQty: {
    alignSelf: "flex-start",
    fontSize: 12,
    lineHeight: 16,
    color: "#111827",
    borderRadius: 2,
    paddingHorizontal: 3,
    paddingVertical: 2,
  },
  itemPrice: {
    fontSize: 12,
    lineHeight: 20,
    color: "#111827",
    minWidth: 36,
    textAlign: "right",
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 2,
  },
  billDetailsWrap: {
    gap: 4,
    paddingVertical: 2,

  },
  billHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  billHeaderTitle: {
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 4,
  },
  billRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  billRowLabel: {
    fontSize: 12,
    lineHeight: 18,
  },
  billRowValue: {
    fontSize: 12,
    lineHeight: 18,
    textAlign: "right",
  },
  billNoteText: {
    fontSize: 11,
    lineHeight: 16,
    marginTop: 2,
  },
  totalLabel: {
    fontSize: 16,
    lineHeight: 24,
    color: "#111827",
  },
  totalValue: {
    fontSize: 16,
    lineHeight: 24,
    color: "#111827",
  },
  commentBox: {
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 6,
  },
  commentLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: "#4B5563",
  },
  commentText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#111827",
    fontStyle: "italic",
  },
  actions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 2,
  },
  btn: {
    flex: 1,
    height: 42,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  btnReject: {
    borderWidth: 1.5,
    borderColor: "#EF4444",
    backgroundColor: "transparent",
  },
  btnRejectText: {
    fontSize: 16,
    lineHeight: 24,
  },
  btnAccept: {},
  btnAcceptText: {
    fontSize: 16,
    lineHeight: 24,
  },
  // In Progress specific styles
  riderStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FEE2E2",
    borderColor: "#FCA5A5",
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 50,
    alignSelf: "flex-start",
    marginBottom: 4,
  },
  riderStatusText: {
    fontSize: 12,
    color: "#B91C1C",
    fontWeight: "500",
  },
  riderInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  riderInfoText: {
    fontSize: 12,
    color: "#4B5563",
  },
  preparingStatusBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 10,
    borderRadius: 6,
    marginTop: 6,
  },
  preparingLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  preparingText: {
    fontSize: 14,
    color: "#047857",
    fontWeight: "500",
  },
  timerText: {
    fontSize: 20,
    color: "#047857",
    fontWeight: "600",
  },
  inProgressActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  btnPlusTime: {
    paddingHorizontal: 14,
    height: 42,
    borderRadius: 40,
    borderWidth: 1,
    borderColor: "#E4E4E7",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  btnPlusTimeText: {
    fontSize: 16,
    color: "#374151",
    fontWeight: "500",
  },
  btnMarkReady: {
    flex: 1,
    height: 42,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  btnMarkReadyText: {
    fontSize: 16,
    fontWeight: "500",
  },
  // Ready specific styles
  readyTopRow: {
    flexDirection: "column",
    alignItems: "flex-start",
    marginTop: 8,
    gap: 4,
  },
  readyStatusColumn: {
    flex: 1,
    gap: 6,
    paddingRight: 4,
  },
  readyRiderBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#D1FAE5",
    borderColor: "#A7F3D0",
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 50,
  },
  readyRiderText: {
    fontSize: 12,
    lineHeight: 16,
    color: "#059669",
    fontWeight: "500",
  },
  pickupRiderBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FEF9C3",
    borderColor: "#FDE047",
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 50,
  },
  pickupRiderText: {
    fontSize: 12,
    lineHeight: 16,
    color: "#CA8A04",
    fontWeight: "500",
  },
  actionButtonsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  iconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  iconBtnDisabled: {
    opacity: 0.5,
  },
  badge: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: "#EF4444",
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#FFFFFF",
  },
  badgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "bold",
  },
  riderDetailsBox: {
    backgroundColor: "#F3F4F6",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 6,
    width: "100%",
    gap: 3,
  },
  riderNameText: {
    fontSize: 13,
    lineHeight: 18,
  },
  riderAssignedCompact: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flex: 1,
  },
  riderVehicleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  riderVehicleText: {
    fontSize: 12,
    lineHeight: 16,
    color: "#4B5563",
  },
  btnConfirmPickup: {
    height: 42,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  btnConfirmPickupText: {
    fontSize: 16,
    fontWeight: "600",
  },
  confirmPickupContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  confirmPickupIconCircle: {
    width: 18,
    height: 18,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  // Completed specific styles
  completedRiderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 6,
    marginBottom: 10,
  },
  completedWrap: {
    gap: 10,
  },
  completedTopMetaBox: {
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 6,
  },
  completedTopMetaCol: {
    flex: 1,
    gap: 8,
  },
  completedStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 2,
  },
  completedStatusLabel: {
    fontSize: 14,
    lineHeight: 18,
    color: "#4B5563",
  },
  completedRiderInfo: {
    gap: 4,
  },
  completedRiderLabel: {
    fontSize: 12,
  },
  completedRiderName: {
    fontSize: 15,
  },
  completedFooterCol: {
    gap: 4,
  },
  completedFooterLabel: {
    fontSize: 12,
  },
  completedFooterValue: {
    fontSize: 14,
  },
  riderArrivedBadge: {
    backgroundColor: "#D1FAE5",
    borderColor: "#A7F3D0",
  },
});
